export default {
    artanis: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/c/c0/Artanis_square_tile.png/revision/latest?cb=20190326222748",
        urlHeroName: "artanis",
        buildsURL: "https://heroeshearth.com/builds/hero/artanis",

        talents: {
            1: ["Reactive Parry", "Amateur Opponent", "Seasoned Marksman"],
            4: ["Psionic Synergy", "Shield Battery Artanis", "Shield Surge"],
            7: [
                "Solarite Reaper",
                "Warp Sickness",
                "Chrono Surge",
                "Final Cut Artanis",
            ],
            10: ["Suppression Pulse", "Purifier Beam"],
            13: [
                "Templars Zeal",
                "Triple Strike",
                "Graviton Vortex",
                "Phase Bulwark",
            ],
            16: ["Titan Killer", "Force Of Will", "Blades Of A Templar"],
            20: [
                "Orbital Bombardment",
                "Target Purified",
                "Zealot Charge",
                "Plasma Burn",
            ],
        },
    },
    chen: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/c/c0/Chen_square_tile.png/revision/latest?cb=20190326222754",
        urlHeroName: "chen",
        buildsURL: "https://heroeshearth.com/builds/hero/chen",

        talents: {
            1: [
                "Eye Of The Tiger",
                "Freshest Ingredients",
                "Stormstout Secret Recipe",
            ],
            4: ["Deadly Strike", "Accumulating Flame", "Withering Flames"],
            7: ["Gift Of The Ox", "Brewmasters Balance", "Elusive Brawler"],
            10: ["Wandering Keg", "Storm Earth Fire"],
            13: [
                "Pressure Point",
                "A Touch Of Honey",
                "Ring Of Fire",
                "Enough To Share",
            ],
            16: ["Flying Leap", "Celerity", "Combo Strikes"],
            20: [
                "Untapped Potential",
                "Elemental Conduit",
                "Purifying Brew",
                "Energizing Brew",
            ],
        },
    },
    dva: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/d/d8/D.va_square_tile.png/revision/latest?cb=20190326222758",
        urlHeroName: "dva",
        buildsURL: "https://heroeshearth.com/builds/hero/dva",

        talents: {
            1: ["Full Metal", "Liquid Cooling", "Pro Moves"],
            4: ["Rush Down", "Aggression Matrix", "Nuclear Option"],
            7: ["Get On The Point", "Hit The Nitrous", "Fusion Generator"],
            10: ["Bunny Hop", "Micro Missiles"],
            13: ["Target Locked", "Good To Go", "Pew Pew Pew"],
            16: [
                "In For The Kill Dva",
                "Diverting Power",
                "Emergency Shielding",
            ],
            20: [
                "Stop And Pop",
                "Timing Attack",
                "Headshot Dva",
                "Ablative Armor",
            ],
        },
    },
    deathwing: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/81/Deathwing_square_tile.png/revision/latest?cb=20201119010931",
        urlHeroName: "deathwing",
        buildsURL: "https://heroeshearth.com/builds/hero/deathwing",
        talents: {
            1: ["Dragon Soul", "Molten Blood", "Draconic Might"],
            4: ["Infernus", "Heat Wave", "Dragons Ire"],
            7: ["Firestorm", "Death Drop", "Skyfall"],
            10: ["Burn Beneath My Shadow", "Bellowing Roar"],
            13: ["Wicked Inferno", "Ruination", "Fire And Fury"],
            16: [
                "Conflagration",
                "Gaze Onto Destruction",
                "Elementium Plating",
            ],
            20: ["Stood In The Fire", "Arrival Of A God", "Destroyers Rampage"],
        },
    },
    dehaka: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/f/f0/Dehaka_square_tile.png/revision/latest?cb=20190326222800",
        urlHeroName: "dehaka",
        buildsURL: "https://heroeshearth.com/builds/hero/dehaka",
        talents: {
            1: ["Enduring Swarm", "Tissue Regeneration", "Enhanced Agility"],
            4: ["Lurker Strain", "One Who Collects", "Hero Stalker"],
            7: ["Feeding Frenzy", "Paralyzing Enzymes", "Symbiosis"],
            10: ["Isolation", "Adaptation"],
            13: ["Ferocious Stalker", "Primal Swarm", "Primal Rage"],
            16: ["Elongated Tongue", "Tunneling Claws", "Pack Leader"],
            20: [
                "Contagion",
                "Change Is Survival",
                "Essence Claws",
                "Apex Predator",
            ],
        },
    },
    gazlowe: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/3/36/Gazlowe_square_tile.png/revision/latest?cb=20201122030838",
        urlHeroName: "gazlowe",
        buildsURL: "https://heroeshearth.com/builds/hero/gazlowe",
    },
    hogger: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/d/d0/Hogger_square_tile.png/revision/latest?cb=20201229013046",
        urlHeroName: "hogger",
        buildsURL: "https://heroeshearth.com/builds/hero/hogger",
        talents: {
            1: ["Journeyman Cooking", "Bones To Gnaw", "On The Prowl Hogger"],
            4: ["Brute Strength", "Aggro Range", "Hoggers Joggers"],
            7: ["Seeing Red", "Dense Blasting Powder", "Garbage Fire"],
            10: ["Hoardapult", "Shockwave"],
            13: ["Dust Devil", "Pummel", "Bloodthirst Hogger"],
            16: ["Headbanger", "Kablooie", "Furzerker"],
            20: [
                "Secret Stash",
                "Power Spike",
                "No Control",
                "Anger Management Hogger",
            ],
        },
    },
    imperius: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/a/a5/Imperius_square_tile.png/revision/latest?cb=20190326222821",
        urlHeroName: "imperius",
        buildsURL: "https://heroeshearth.com/builds/hero/imperius",
        talents: {
            1: ["Impaling Light", "Consuming Flame", "Burn The Impure"],
            4: ["Sovereign Armor", "Battle Hunger", "Press Forward"],
            7: ["Flash Of Anger", "Blaze Of Glory", "Holy Fervor"],
            10: ["Angelic Armaments", "Wrath Of The Angiris"],
            13: ["Pathetic Mortals", "Divine Rage", "Heat Of Battle"],
            16: ["Celestial Swiftness", "Melting Touch", "Valorous Pursuit"],
            20: [
                "Heavenly Host",
                "Unrelenting Descent",
                "Brand Of Solarion",
                "Impervious",
            ],
        },
    },
    leoric: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/6/6c/Leoric_square_tile.png/revision/latest?cb=20190326222832",
        urlHeroName: "leoric",
        buildsURL: "https://heroeshearth.com/builds/hero/leoric",
        talents: {
            1: ["Consume Vitality", "Fealty Unto Death", "Ossein Renewal"],
            4: ["Ghastly Reach", "Paralyzing Rage", "Kneel Peasants"],
            7: ["Willing Vessel", "Drain Momentum", "Hopelessness"],
            10: ["Entomb", "March Of The Black King"],
            13: ["Unyielding Despair", "Ominous Wraith", "Spectral Leech"],
            16: ["Crushing Hope", "Royal Focus", "Mithril Mace"],
            20: [
                "Buried Alive",
                "Death March",
                "Burning Despair",
                "Shroud Of The Dead King",
            ],
        },
    },
    malthael: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/d/d0/Malthael_square_tile.png/revision/latest?cb=20190326222840",
        urlHeroName: "malthael",
        buildsURL: "https://heroeshearth.com/builds/hero/malthael",
        talents: {
            1: ["Deaths Reach", "On A Pale Horse", "Fear The Reaper"],
            4: ["Die Alone", "Throwing Shade", "Black Harvest"],
            7: ["Cold Hand", "Massacre", "Touch Of Death"],
            10: ["Tormented Souls", "Last Rites"],
            13: [
                "Soul Siphon",
                "Ethereal Existence",
                "Inevitable End",
                "Shroud Of Wisdom",
            ],
            16: ["Soul Collector", "Mortality", "Memento Mori"],
            20: [
                "Reaper Of Souls",
                "Angel Of Death",
                "Final Curtain",
                "No One Can Stop Death",
            ],
        },
    },
    ragnaros: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/d/d6/Ragnaros_square_tile.png/revision/latest?cb=20190326222853",
        urlHeroName: "ragnaros",
        buildsURL: "https://heroeshearth.com/builds/hero/ragnaros",
        talents: {
            1: ["Sulfuras Hungers", "Shifting Meteor", "Engulfing Flame"],
            4: ["Fire Ward", "Slow Burn", "Catching Fire"],
            7: ["Hand Of Ragnaros", "Molten Power", "Blistering Attacks"],
            10: ["Sulfuras Smash", "Lava Wave"],
            13: ["Cauterize Wounds", "Tempered Flame", "Resilient Flame"],
            16: ["Giant Scorcher", "Meteor Bomb", "Blast Echo"],
            20: [
                "Flames Of Sulfuron",
                "Lava Surge",
                "Heroic Difficulty",
                "Submerge",
            ],
        },
    },
    rexxar: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/80/Rexxar_square_tile.png/revision/latest?cb=20190326222855",
        urlHeroName: "rexxar",
        buildsURL: "https://heroeshearth.com/builds/hero/rexxar",
        talents: {
            1: ["Bird Of Prey", "Easy Prey", "Flare"],
            4: [
                "Hungry Bear",
                "Hunter Gatherer",
                "Grizzled Fortitude",
                "Animal Husbandry",
            ],
            7: ["Crippling Talons", "Taking Flight", "Aspect Of The Beast"],
            10: ["Bestial Wrath", "Unleash The Boars"],
            13: ["Aspect Of The Hawk", "Dire Beast", "Wildfire Bear"],
            16: ["Thrill Of The Hunt", "Primal Intimidation", "Feign Death"],
            20: [
                "Spirit Bond",
                "Kill Command",
                "Frenzy Of Kalimdor",
                "Hardened Skin",
            ],
        },
    },
    sonya: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/e/eb/Sonya_square_tile.png/revision/latest?cb=20190326222859",
        urlHeroName: "sonya",
        buildsURL: "https://heroeshearth.com/builds/hero/sonya",
        talents: {
            1: ["Furious Blow", "War Paint", "Tough As Nails"],
            4: ["Shattered Ground", "Hurricane", "Shot Of Fury"],
            7: ["Poisoned Spear", "Life Funnel", "Battle Rage"],
            10: ["Leap", "Wrath Of The Berserker"],
            13: ["Mystical Spear", "Ruthless", "No Escape"],
            16: ["Giant Slammer", "Rampage", "Nerves Of Steel"],
            20: [
                "Arreat Crater",
                "Striding Giant",
                "Composite Spear",
                "Ignore Pain",
            ],
        },
    },
    thrall: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/f/f0/Thrall_square_tile.png/revision/latest?cb=20190326222906",
        urlHeroName: "thrall",
        buildsURL: "https://heroeshearth.com/builds/hero/thrall",
        talents: {
            1: ["Echo Of The Elements", "Crash Lightning", "Rolling Thunder"],
            4: ["Feral Resilience", "Frostwolf Pack", "Mana Tide"],
            7: ["Maelstrom Weapon", "Ancestral Wrath", "Follow Through"],
            10: ["Sundering", "Earthquake"],
            13: ["Grace Of Air", "Frostwolfs Grace", "Spirit Shield"],
            16: ["Tempest Fury", "Thunderstorm", "Alpha Wolf"],
            20: [
                "Worldbreaker",
                "Earthen Shields",
                "Elemental Momentum",
                "Nexus Blades",
                "Wind Rush",
            ],
        },
    },
    varian: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/d/d9/Varian_square_tile.png/revision/latest?cb=20190326222914",
        urlHeroName: "varian",
        buildsURL: "https://heroeshearth.com/builds/hero/varian",
        talents: {
            1: ["Lions Maw", "Overpower Varian", "High Kings Quest"],
            4: ["Taunt", "Colossus Smash", "Twin Blades Of Fury"],
            7: ["Lionheart", "Second Wind", "Victory Rush"],
            10: ["Shield Wall", "Warbringer"],
            13: ["Juggernaut", "Mortal Strike", "Shattering Throw"],
            16: [
                "Banner Of Stormwind",
                "Banner Of Ironforge",
                "Banner Of Dalaran",
            ],
            20: [
                "Vigilance",
                "Master At Arms",
                "Frenzy",
                "Glory To The Alliance",
                "Demoralizing Shout",
            ],
        },
    },
    xul: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/f/fc/Xul_square_tile.png/revision/latest?cb=20190326222915",
        urlHeroName: "xul",
        buildsURL: "https://heroeshearth.com/builds/hero/xul",
        talents: {
            1: ["Backlash", "Shackler", "Shade"],
            4: ["Reapers Toll", "Grim Scythe", "Jailors"],
            7: ["Harvest Vitality", "Tragouls Essence", "Wall Of Bones"],
            10: ["Poison Nova", "Skeletal Mages"],
            13: ["Echoes Of Death", "Rapid Harvest", "Amplify Damage"],
            16: ["Decrepify", "Weaken", "Bone Spear"],
            20: [
                "Andariels Visage",
                "Cold Hand Of Death",
                "Mortal Wound",
                "Kalans Edict",
            ],
        },
    },
    yrel: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/0a/Yrel_square_tile.png/revision/latest?cb=20190326222916",
        urlHeroName: "yrel",
        buildsURL: "https://heroeshearth.com/builds/hero/yrel",
        talents: {
            1: ["Light Of Karabor", "Dauntless", "Maraads Insight"],
            4: ["Aegis Of Light", "Gift Of The Naaru", "Hand Of Freedom"],
            7: [
                "Righteous Momentum",
                "Holy Avenger",
                "Divine Steed",
                "Samaaras Light",
            ],
            10: ["Ardent Defender", "Sacred Ground"],
            13: ["Aldor Peacekeeper", "Repentance", "Velens Chosen"],
            16: ["Templars Verdict", "Divine Favor", "Holy Wrath"],
            20: [
                "Word Of Glory",
                "Hallowed Ground",
                "Bubble Hearth",
                "Seraphim",
            ],
        },
    },
    alexstrasza: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/2/21/Alexstrasza_square_tile.png/revision/latest?cb=20190326222744",
        urlHeroName: "alexstrasza",
        buildsURL: "https://heroeshearth.com/builds/hero/alexstrasza",
        talents: {
            1: [
                "Live And Let Live",
                "Circle Of Life Alexstrasza",
                "Flames Of Fury",
            ],
            4: ["Surge Of Vitality", "Heat Exhaustion", "Exuberance"],
            7: ["Lifeblossom", "Verdant Flourish", "Fire Within"],
            10: ["Life Binder", "Cleansing Flame"],
            13: ["Dragon Scales", "Pacify", "Life Unbound"],
            16: ["Tough Love", "Overprotective", "Draconic Discipline"],
            20: [
                "Ritual Of Life",
                "On Ruby Wings",
                "Ancient Flame",
                "Blessing Of The Red",
            ],
        },
    },
    ana: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/0b/Ana_square_tile.png/revision/latest?cb=20190326222746",
        urlHeroName: "ana",
        buildsURL: "https://heroeshearth.com/builds/hero/ana",
        talents: {
            1: ["Contact Healing", "Slumber Shells", "Vampiric Rounds"],
            4: ["Biotic Enhancements", "Overdose", "Debilitating Dart"],
            7: ["Anti Healer", "Night Terrors", "Mind Numbing Agent"],
            10: ["Nano Boost", "Eye Of Horus"],
            13: ["Speed Serum", "Purifying Darts", "Smelling Salts"],
            16: ["Sharpshooter", "Concentrated Doses", "Active Reload"],
            20: [
                "Nano Infusion",
                "Deadeye",
                "Armored Stance",
                "Dynamic Optics",
            ],
        },
    },
    anduin: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/a/ae/Anduin_square_tile.png/revision/latest?cb=20190423162644",
        urlHeroName: "anduin",
        buildsURL: "https://heroeshearth.com/builds/hero/anduin",
        talents: {
            1: [
                "Pursued By Grace",
                "Bold Strategy",
                "Evenhanded Blessings",
                "Power Word Shield",
                "Lightwell",
            ],
            4: [
                "Moral Compass",
                "Holy Reach",
                "Surge Of Light Anduin",
                "Piercing Light",
            ],
            7: ["Binding Heal", "Blessed Recovery", "Desperate Prayer"],
            10: ["Hold Word Salvation", "Lightbomb"],
            13: [
                "Speed Of The Pious",
                "Enchant Boots Lions Speed",
                "Push Forward",
            ],
            16: ["Holy Nova", "Renew", "Glyph Of Faith", "Inner Focus"],
            20: [
                "Light Of Stormwind",
                "Varians Legacy",
                "Inner Fire",
                "Censure",
            ],
        },
    },
    auriel: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/4/43/Auriel_square_tile.png/revision/latest?cb=20190326222750",
        urlHeroName: "auriel",
        buildsURL: "https://heroeshearth.com/builds/hero/auriel",
        talents: {
            1: ["Increasing Clarity", "Righteous Assault", "Searing Light"],
            4: ["Majestic Span", "Heavy Burden", "Repeated Offense"],
            7: ["Glimmer Of Hope", "Empathic Link", "Energized Cord"],
            10: ["Resurrect", "Crystal Aegis"],
            13: ["Blinding Flash", "Converging Force", "Piercing Lash"],
            16: ["Reservoir Of Hope", "Will Of Heaven", "Wrath Of Heaven"],
            20: [
                "Light Speed",
                "Diamond Resolve",
                "Angelic Flight",
                "Shield Of Hope",
            ],
        },
    },
    brightwing: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/e/e4/Brightwing_square_tile.png/revision/latest?cb=20190326222752",
        urlHeroName: "brightwing",
        buildsURL: "https://heroeshearth.com/builds/hero/brightwing",
        talents: {
            1: ["Greater Polymorph", "Hyper Shift", "Pixie Charm"],
            4: ["Dream Shot", "Unstable Anomaly", "Magic Spit"],
            7: ["Sticky Flare", "Peekaboo", "Critical Mist"],
            10: ["Blink Heal", "Emerald Wind"],
            13: ["Pixie Boost", "Safety Dust", "Pixie Power"],
            16: ["Hush", "Critterize", "Phase Out"],
            20: [
                "Invisible Friends",
                "Intensive Winds",
                "Speedy Dragon",
                "Faerie Protector",
            ],
        },
    },
    deckard: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/c/c6/Deckard_square_tile.png/revision/latest?cb=20190326222758",
        urlHeroName: "deckard",
        buildsURL: "https://heroeshearth.com/builds/hero/deckard",
        talents: {
            1: ["Scroll Of Identify", "Field Study", "Sapphire"],
            4: ["Potion Of Shielding", "Rejuvenation Potion", "Ruby"],
            7: ["Cube Mastery", "Kanais Cube", "Emerald"],
            10: ["Stay Awhile And Listen", "Lorenado"],
            13: [
                "Super Healing Potion",
                "Potion Of Revival",
                "Ancient Blessings",
            ],
            16: [
                "Scroll Of Stone Curse",
                "Safety In Numbers",
                "Horadric Staff",
            ],
            20: [
                "Respect The Elderly",
                "Morenados",
                "Bottomless Flask",
                "Perfect Gems",
            ],
        },
    },
    kharazim: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/8a/Kharazim_square_tile.png/revision/latest?cb=20190326222831",
        urlHeroName: "kharazim",
        buildsURL: "https://heroeshearth.com/builds/hero/kharazim",
        talents: {
            1: ["Transcendence", "Iron Fists", "Insight"],
            4: ["Spirit Ally", "Earth Ally", "Air Ally"],
            7: ["Blinding Speed", "Heavenly Zeal", "Blazing Fists"],
            10: ["Divine Palm", "Seven Sided Strike"],
            13: ["Quicksilver", "Spell Shield", "Sixth Sense Kharazim"],
            16: [
                "Cleansing Touch",
                "Way Of The Hundred Fists",
                "Echo Of Heaven",
            ],
            20: [
                "Peaceful Repose",
                "Transgression",
                "Storm Shield",
                "Epiphany",
                "Fists Of Legend",
            ],
        },
    },
    "li-li": {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/82/Li_li_square_tile.png/revision/latest?cb=20190326222832",
        urlHeroName: "li-li",
        buildsURL: "https://heroeshearth.com/builds/hero/li-li",
        talents: {
            1: ["Free Drinks", "Serpent Sidekick", "Eager Adventurer"],
            4: ["Wind Serpent", "Surging Winds", "Safety Sprint"],
            7: ["The Good Stuff", "Mass Vortex", "Lets Go"],
            10: ["Jug Of 1000 Cups", "Water Dragon"],
            13: ["Gale Force", "Hindering Winds", "Lightning Serpent"],
            16: ["Two For One", "Pick Me Up", "Blessings Of Yulon"],
            20: [
                "Jug Of 1000000 Cups",
                "Double Dragon",
                "Mistweaver",
                "Shake It Off",
            ],
        },
    },
    "lt-morales": {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/1/18/Lt._morales_square_tile.png/revision/latest?cb=20190326222835",
        urlHeroName: "lt-morales",
        buildsURL: "https://heroeshearth.com/builds/hero/lt-morales",
        talents: {
            1: ["Caduceus Feedback", "Life Support", "Clear"],
            4: ["Cellular Reactor", "Trauma Trigger", "Blast Shield"],
            7: ["Physical Therapy", "Vanadium Plating", "Medi Drone"],
            10: ["Stim Drone", "Medivac Dropship"],
            13: ["Emp Grenade", "System Shock", "Bedside Manner"],
            16: ["Extended Care", "First Responder", "Shield Sequencer"],
            20: [
                "Hyperactivity",
                "Safe Zone",
                "Caduceus Reactor 20",
                "Second Opinion",
                "Hospice Care",
            ],
        },
    },
    lucio: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/4/42/L%C3%BAcio_square_tile.png/revision/latest?cb=20190326222835",
        urlHeroName: "lucio",
        buildsURL: "https://heroeshearth.com/builds/hero/lucio",
        talents: {
            1: ["Party Mix", "Accelerando", "Smooth Moves"],
            4: ["Subwoofer", "Off The Wall", "Supersonic"],
            7: ["Good Vibrations", "Reverse Amp", "Boombox"],
            10: ["Sound Barrier", "High Five"],
            13: ["All Together", "Heavy Casters", "Slip"],
            16: ["Rejuvenesc Ncia", "Up The Frequency", "Up To Eleven"],
            20: ["Bossa Nova", "Mixing Fire", "House Party", "Summer Anthem"],
        },
    },
    malfurion: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/c/cd/Malfurion_square_tile.png/revision/latest?cb=20190326222838",
        urlHeroName: "malfurion",
        buildsURL: "https://heroeshearth.com/builds/hero/malfurion",
        talents: {
            1: ["Deep Roots", "Emerald Dreams", "Vengeful Roots"],
            4: ["Rejuvenation", "Celestial Alignment", "Shandos Clarity"],
            7: ["Wild Growth", "Tenacious Roots", "Natures Cure"],
            10: ["Tranquility", "Twilight Dream"],
            13: ["Natures Swiftness", "Hindering Moonfire", "Revitalize"],
            16: ["Yseras Gift", "Natures Balance", "Moonlit Harmony"],
            20: ["Serenity", "Astral Communion", "Lifebloom", "Lunar Shower"],
        },
    },
    reghar: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/a/aa/Rehgar_square_tile.png/revision/latest?cb=20190326222855",
        urlHeroName: "reghar",
        buildsURL: "https://heroeshearth.com/builds/hero/reghar",
    },
    stukov: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/6/6a/Stukov_square_tile.png/revision/latest?cb=20190326222900",
        urlHeroName: "stukov",
        buildsURL: "https://heroeshearth.com/builds/hero/stukov",
    },
    tyrande: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/87/Tyrande_square_tile.png/revision/latest?cb=20190326222910",
        urlHeroName: "tyrande",
        buildsURL: "https://heroeshearth.com/builds/hero/tyrande",
    },
    uther: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/2/20/Uther_square_tile.png/revision/latest?cb=20190326222911",
        urlHeroName: "uther",
        buildsURL: "https://heroeshearth.com/builds/hero/uther",
    },
    whitemane: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/7/7b/Whitemane_square_tile.png/revision/latest?cb=20190326222914",
        urlHeroName: "whitemane",
        buildsURL: "https://heroeshearth.com/builds/hero/whitemane",
    },
    alarak: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/1/11/Alarak_square_tile.png/revision/latest?cb=20190326222744",
        urlHeroName: "alarak",
        buildsURL: "https://heroeshearth.com/builds/hero/alarak",

        talents: {
            1: ["Sustaining Power", "Extended Lightning", "Ruthless Momentum"],
            4: ["Chaos Reigns", "Negatively Charged", "Show Of Force"],
            7: ["Dissonance", "Hindered Motion", "Applied Force"],
            10: ["Deadly Charge", "Counter Strike"],
            13: ["Blade Of The Highlord", "Pure Malice", "Rite Of Rakshir"],
            16: ["Lethal Onslaught", "Lightning Barrage", "Mocking Strikes"],
            20: [
                "Counter Strike",
                "Deadly Charge",
                "Last Laugh",
                "Hasty Bargain",
            ],
        },
    },
    illidan: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/6/69/Illidan_square_tile.png/revision/latest?cb=20190326222819",
        urlHeroName: "illidan",
        buildsURL: "https://heroeshearth.com/builds/hero/illidan",
        talents: {
            1: ["Immolation", "Battered Assault", "Unending Hatred"],
            4: ["Reflexive Block", "Thirsting Blade", "Hunters Onslaught"],
            7: ["Rapid Chase", "Friend Or Foe", "Unbound"],
            10: ["Metamorphosis", "The Hunt"],
            13: ["Nimble Defender", "Elusive Strike", "Sixth Sense Illidan"],
            16: ["Marked For Death", "Fiery Brand", "Blades Of Azzinoth"],
            20: [
                "Demonic Form",
                "Nowhere To Hide",
                "Nexus Blades",
                "Bolt Of The Storm",
            ],
        },
    },
    kerrigan: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/6/64/Kerrigan_square_tile.png/revision/latest?cb=20190326222829",
        urlHeroName: "kerrigan",
        buildsURL: "https://heroeshearth.com/builds/hero/kerrigan",
        talents: {
            1: [
                "Siphoning Impact",
                "Assimilation Mastery",
                "Fury Of The Swarm",
            ],
            4: ["Sharpened Blades", "Kinetic Fulmination", "Psionic Pulse"],
            7: ["Queen Of Blades", "Boundless Fury", "Bladed Momentum"],
            10: ["Maelstrom", "Summon Ultralisk"],
            13: ["Psionic Barrier", "Volatile Power", "Chrysalis"],
            16: ["Mounting Potency", "Painful Spikes", "Unbridled Energy"],
            20: [
                "Omegastorm",
                "Torrasque",
                "Assimilation Blades",
                "Psionic Shift",
            ],
        },
    },
    maiev: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/e/e1/Maiev_square_tile.png/revision/latest?cb=20190326222837",
        urlHeroName: "maiev",
        buildsURL: "https://heroeshearth.com/builds/hero/maiev",
        talents: {
            1: ["Bonds Of Justice", "Pursuit Of Vengeance", "Naishas Memento"],
            4: ["Pin Down", "Blade Dance", "Sudden Vengeance"],
            7: ["Elunes Wrath", "Bonds Of Corruption", "Ruthless Spirit"],
            10: ["Containment Disc", "Wardens Cage"],
            13: ["Bladed Armor", "Chain Gang", "Shadow Armor"],
            16: ["Cruel Chain", "Vengeful Knives", "Armored Assault"],
            20: [
                "Shadow Orb Vengeance",
                "Shadow Orb Huntress",
                "Shadow Orb Shadow Strike",
            ],
        },
    },
    murky: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/f/f9/Murky_square_tile.png/revision/latest?cb=20190326222845",
        urlHeroName: "murky",
        buildsURL: "https://heroeshearth.com/builds/hero/murky",
        talents: {
            1: ["Fish Eye", "Egg Hunt", "A Fishy Deal"],
            4: ["Slime Time", "Tufferfish", "Living The Dream"],
            7: ["Black Lagoon", "Slippery When Wet", "Time To Krill"],
            10: ["March Of The Murlocs", "Octo Grab"],
            13: ["Rejuvenating Bubble", "Fish Tank", "Egg Shell"],
            16: ["Toxic Buildup", "Fish Oil", "Wrath Of Cod"],
            20: [
                "Never Ending Murlocs",
                "And A Shark Too",
                "Big Tuna Kahuna",
                "Making Inky",
            ],
        },
    },
    qhira: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/7/7d/Qhira_square_tile.png/revision/latest?cb=20190729232915",
        urlHeroName: "qhira",
        buildsURL: "https://heroeshearth.com/builds/hero/qhira",
        talents: {
            1: ["Maximum Effort", "Fatal Wounds", "Finishing Touch"],
            4: ["Upstage", "Ensnaring Swing", "Your Pain My Gain"],
            7: ["The Thirst", "Healmonger", "Siphoning Link"],
            10: ["Unrelenting Strikes", "Final Strike"],
            13: ["Chainsaw", "Pulsing Pain", "The Hunted"],
            16: ["Booming Kick", "Lingering Ailment", "Swing Life Away"],
            20: [
                "Silent Killer",
                "Unleashed Potential",
                "Utility Belt",
                "No Sanctuary",
            ],
        },
    },
    samuro: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/08/Samuro_square_tile.png/revision/latest?cb=20190326222857",
        urlHeroName: "samuro",
        buildsURL: "https://heroeshearth.com/builds/hero/samuro",
        talents: {
            1: ["Way Of Illusion", "Way Of The Blade", "Way Of The Wind"],
            4: ["Mirage", "One With The Wind", "Deflection"],
            7: ["Burning Blade", "Phantom Pain", "Crushing Blows"],
            10: ["Bladestorm", "Illusion Master"],
            13: ["Mirrored Steel", "Kawarimi", "Shukuchi"],
            16: ["Merciless Strikes", "Harsh Winds", "Press The Attack"],
            20: [
                "Dance Of Death",
                "Three Blade Style",
                "Wind Strider",
                "Blademasters Pursuit",
            ],
        },
    },
    "the-butcher": {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/c/c9/The_butcher_square_tile.png/revision/latest?cb=20190326222903",
        urlHeroName: "the-butcher",
        buildsURL: "https://heroeshearth.com/builds/hero/the-butcher",
        talents: {
            1: ["Invigoration", "Block", "Chop Meat"],
            4: ["Flail Axe", "Unrelenting Pursuit", "Cheap Shot"],
            7: ["Insatiable Blade", "Victuals", "Meat Shield"],
            10: ["Furnace Blast", "Lamb To The Slaughter"],
            13: ["Cleaver", "Savage Charge", "Brutal Strike"],
            16: ["Crippling Slam", "Enraged", "Blood Frenzy"],
            20: [
                "Fires Of Hell",
                "Slaughterhouse",
                "Nexus Blades",
                "Bolt Of The Storm",
            ],
        },
    },
    valeera: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/4/42/Valeera_square_tile.png/revision/latest?cb=20190326222911",
        urlHeroName: "valeera",
        buildsURL: "https://heroeshearth.com/builds/hero/valeera",
        talents: {
            1: ["Vigor", "Subtlety", "Combat Readiness", "Crippling Poison"],
            4: [
                "Relentless Strikes",
                "Hemorrhage",
                "Initiative",
                "Wound Poison",
            ],
            7: ["Mutilate", "Fatal Finesse", "Slice And Dice"],
            10: ["Smoke Bomb", "Cloak Of Shadows"],
            13: ["Death From Above", "Blind", "Strangle"],
            16: ["Seal Fate", "Assassinate", "Thistle Tea"],
            20: [
                "Adrenaline Rush",
                "Enveloping Shadows",
                "Rupture",
                "Elusiveness",
            ],
        },
    },
    zeratul: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/9/9d/Zeratul_square_tile.png/revision/latest?cb=20190326222919",
        urlHeroName: "zeratul",
        buildsURL: "https://heroeshearth.com/builds/hero/zeratul",
        talents: {
            1: ["Greater Cleave", "Shadow Hunter", "Move Unseen"],
            4: ["Rending Cleave", "Psionic Strength", "Darkness Descends"],
            7: ["Wormhole", "Seeker In The Dark", "Warp Skirmisher"],
            10: ["Might Of The Nerazim", "Void Prison"],
            13: ["Shroud Of Adun", "Mending Strikes", "Spell Shield"],
            16: ["Master Warp Blade", "Void Slash", "Sentenced To Death"],
            20: [
                "Twilight Falls",
                "Unwavering Pressure",
                "Shadow Stride",
                "Shadow Mending",
            ],
        },
    },
    azmodan: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/9/95/Azmodan_square_tile.png/revision/latest?cb=20190326222750",
        urlHeroName: "azmodan",
        buildsURL: "https://heroeshearth.com/builds/hero/azmodan",
        talents: {
            1: ["Greed", "Gluttony", "Wrath"],
            4: ["Army Of Hell", "Hellforged Armor", "Battleborn"],
            7: ["Art Of Chaos", "Bombardment", "Master Of Destruction"],
            10: ["Demonic Invasion", "Tide Of Sin"],
            13: ["Brutish Vanguard", "Cydaeas Kiss", "Chain Of Command"],
            16: ["Total Annihilation", "Hell Rift", "Sins Grasp"],
            20: ["Siegebreaker", "Black Pool Deprecated", "Pride", "Trample"],
        },
    },
    cassia: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/7/7b/Cassia_square_tile.png/revision/latest?cb=20190326222754",
        urlHeroName: "cassia",
        buildsURL: "https://heroeshearth.com/builds/hero/cassia",
        talents: {
            1: ["Thunderstroke", "Impale", "Charged Strikes"],
            4: ["Plate Of The Whale", "Ring Of The Leech", "Inner Light"],
            7: ["Grounding Rod", "Seraphs Hymn", "Surge Of Light"],
            10: ["Ball Lightning", "Valkyrie"],
            13: ["War Matron", "War Traveler", "Gloves Of Alacrity"],
            16: ["Power Strike", "Static Electricity", "Martial Law"],
            20: [
                "Infinite Lightning",
                "Imprisoning Light",
                "Titans Revenge",
                "Rockstopper",
            ],
        },
    },
    chromie: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/5/52/Chromie_square_tile.png/revision/latest?cb=20190326222756",
        urlHeroName: "chromie",
        buildsURL: "https://heroeshearth.com/builds/hero/chromie",
        talents: {
            1: [
                "Once Again The First Time",
                "Deep Breathing",
                "Timewalker's Pursuit",
            ],
            2: ["Chronic Conditions", "Time Troubles", "Andorhal Anomaly"],
            5: ["Bronze Talons", "Mobius Loop", "A Proper Greeting"],
            8: ["Slowing Sands", "Temporal Loop"],
            11: ["Gnome Speed Ahead", "Here And There", "Time Out"],
            14: ["Shifting Sands", "Fast Forward", "Quantum Overdrive"],
            18: [
                "Unravelling",
                "Stuck in a Loop",
                "Piercing Sands",
                "Blessing Of The Bronze",
            ],
        },
    },
    falstad: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/a/ac/Falstad_square_tile.png/revision/latest?cb=20190326222804",
        urlHeroName: "falstad",
        buildsURL: "https://heroeshearth.com/builds/hero/falstad",
        talents: {
            1: ["Gathering Storm", "Dishonorable Discharge", "Frequent Flyer"],
            4: ["Static Shield", "Updraft", "Hammer Gains"],
            7: ["Secret Weapon", "Boomerang", "Charged Up"],
            10: ["Hinterland Blast", "Mighty Gust"],
            13: ["Thunderstrikes", "Flow Rider", "Sustained Winds"],
            16: ["Crippling Hammer", "Aerie Gusts", "Afterburner"],
            20: [
                "Call Of The Wildhammer",
                "Wind Tunnel",
                "Nexus Frenzy",
                "Epic Mount",
            ],
        },
    },
    fenix: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/1/1d/Fenix_square_tile.png/revision/latest?cb=20190326222806",
        urlHeroName: "fenix",
        buildsURL: "https://heroeshearth.com/builds/hero/fenix",
        talents: {
            1: ["Advanced Targeting", "Arsenal Synergy", "Mobile Offense"],
            4: ["Target Acquired", "Inhibiting Energy", "Emergency Protocol"],
            7: ["Combat Advantage", "Warp Warfare", "Diver Power Weapons"],
            10: ["Purification Salvo", "Planet Cracker"],
            13: [
                "Adanium Shell",
                "Dampening Field",
                "Rapid Recharge",
                "Auxiliary Shields",
            ],
            16: [
                "Offensive Cadence",
                "Photonic Weaponry",
                "Arsenal Overcharge",
            ],
            20: [
                "Secondary Fire",
                "Singularity Charge",
                "Unconquered Spirit",
                "Armageddon Beam",
            ],
        },
    },
    gall: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/02/Gall_square_tile.png/revision/latest?cb=20190326222807",
        urlHeroName: "gall",
        buildsURL: "https://heroeshearth.com/builds/hero/gall",
        talents: {
            1: ["Keep Moving", "Taskmaster", "We See You"],
            4: ["Rising Dread", "Runic Persistence", "Bombs Away"],
            7: ["Edge Of Madness", "Double Trouble", "Ogre Rampage"],
            10: ["Shadow Bolt Volley", "Twisting Nether"],
            13: ["Searing Shadows", "Psychotic Break", "Twilight Nova"],
            16: ["Shadowsnare", "Leaden Orb", "Deafening Blast Gall"],
            20: [
                "Shadowfury",
                "Shifting Nether",
                "The Will Of Gall",
                "Twilight Frenzy",
            ],
        },
    },
    genji: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/0d/Genji_square_tile.png/revision/latest?cb=20190326222813",
        urlHeroName: "genji",
        buildsURL: "https://heroeshearth.com/builds/hero/genji",
        talents: {
            1: ["Swift As The Wind", "Agile Dismount", "Pathfinder"],
            4: ["Shuriken Mastery", "Strike At The Heart", "Dragon Claw"],
            7: ["Augmented Guard", "Perfect Defense", "Cyber Shield"],
            10: ["Dragonblade", "X Strike"],
            13: ["Shingan", "Flow Like Water", "Way Of The Shimada"],
            16: ["Reflect", "Final Cut", "Steady Blade"],
            20: [
                "The Dragon Becomes Me",
                "Living Weapon",
                "Sharpened Stars",
                "Zanshin",
            ],
        },
    },
    greymane: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/8e/Greymane_square_tile.png/revision/latest?cb=20190326222815",
        urlHeroName: "greymane",
        buildsURL: "https://heroeshearth.com/builds/hero/greymane",
        talents: {
            1: ["Wolfheart", "Perfect Aim", "Viciousness"],
            4: ["Thick Skin", "Eyes In The Dark", "Insatiable Greymane"],
            7: ["Quicksilver Bullets", "Incendiary Elixir", "Wizened Duelist"],
            10: ["Go For The Throat", "Cursed Bullet"],
            13: ["Running Wild", "On The Prowl", "Unfettered Assault"],
            16: ["Eager Wolf", "Executioner", "Alpha Killer"],
            20: [
                "Unleashed",
                "Gilnean Roulette",
                "Hunters Blunderbuss",
                "Tooth And Claw",
            ],
        },
    },
    guldan: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/d/d4/Gul%27dan_square_tile.png/revision/latest?cb=20190326222816",
        urlHeroName: "guldan",
        buildsURL: "https://heroeshearth.com/builds/hero/guldan",
        talents: {
            1: ["Pursuit Of Flame", "Chaotic Energy", "Echoed Corruption"],
            4: ["Health Funnel", "Improved Life Tap", "Consume Soul"],
            7: ["Bound By Shadow", "Curse Of Exhaustion", "Hunger For Power"],
            10: ["Horrify", "Rain Of Destruction"],
            13: ["Fel Armor", "Harvest Life", "Dark Bargain", "Healthstone"],
            16: ["Rampant Hellfire", "Ruinous Affliction", "Darkness Within"],
            20: ["Haunt", "Deep Impact", "Demonic Circle"],
        },
    },
    hanzo: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/b/bc/Hanzo_square_tile.png/revision/latest?cb=20190326222818",
        urlHeroName: "hanzo",
        buildsURL: "https://heroeshearth.com/builds/hero/hanzo",
        talents: {
            1: ["Target Practice", "Simple Geometry", "Redemption Hanzo"],
            4: [
                "Explosive Arrows",
                "Serrated Arrows",
                "Ignore All Distractions",
            ],
            7: [
                "The Dragon Hungers",
                "Never Outmatched",
                "Sharpened Arrowheads",
            ],
            10: ["Dragonstrike", "Dragons Arrow"],
            13: ["Fleet Of Foot", "Ninja Assassin", "Mounted Archery"],
            16: ["Flawless Technique", "Piercing Arrows", "Giant Slayer"],
            20: [
                "The Dragon Awakens",
                "Play Of The Game",
                "Perfect Agility",
                "Bullseye",
            ],
        },
    },
    jaina: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/7/78/Jaina_square_tile.png/revision/latest?cb=20190326222823",
        urlHeroName: "jaina",
        buildsURL: "https://heroeshearth.com/builds/hero/jaina",
        talents: {
            1: ["Winters Reach", "Lingering Chill", "Fingers Of Frost"],
            4: ["Frost Shards", "Arcane Intellect", "Frost Armor"],
            7: ["Ice Lance", "Ice Floes", "Icefury Wand"],
            10: ["Ring Of Frost", "Summon Water Elemental"],
            13: ["Storm Front", "Ice Barrier", "Icy Veins"],
            16: ["Snowstorm", "Northern Exposure", "Numbing Blast"],
            20: ["Cold Snap", "Wintermute", "Ice Blink", "Deep Chill"],
        },
    },
    junkrat: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/6/69/Junkrat_square_tile.png/revision/latest?cb=20190326222826",
        urlHeroName: "junkrat",
        buildsURL: "https://heroeshearth.com/builds/hero/junkrat",
        talents: {
            1: ["Tricky Shuffles", "Extra Wound Timers", "Blow Em Up"],
            4: ["Taste For Explosions", "Boom Pow", "Chattering Teeth"],
            7: ["Bogged Down", "Sticky Wicket", "Dirty Trickster"],
            10: ["Rip Tire", "Rocket Ride"],
            13: [
                "Bombs Away Junkrat",
                "Ripper Air",
                "Gotta Trap Em All",
                "Big As",
            ],
            16: ["Burst Fire", "Endless Nades", "Spread Volley"],
            20: [
                "Extra Oomph",
                "Puckish Scamp",
                "Cannonball",
                "I Hate Waiting",
            ],
        },
    },
    kaelthas: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/c/c6/Kael%27thas_square_tile.png/revision/latest?cb=20190326222828",
        urlHeroName: "kaelthas",
        buildsURL: "https://heroeshearth.com/builds/hero/kaelthas",
        talents: {
            1: ["Convection", "Fel Infusion", "Mana Addict"],
            4: ["Nether Wind", "Energy Roil", "Mana Tap"],
            7: ["Burned Flesh", "Sun Kings Fury", "Sunfire Enchantment"],
            10: ["Phoenix", "Pyroblast"],
            13: ["Pyromaniac", "Backdraft", "Fission Bomb"],
            16: ["Fury Of The Sunwell", "Ignite", "Twin Spheres"],
            20: [
                "Rebirth",
                "Presence Of Mind",
                "Master Of Flames",
                "Flamethrower",
            ],
        },
    },
    kelthuzad: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/09/Kel%27thuzad_square_tile.png/revision/latest?cb=20190326222828",
        urlHeroName: "kelthuzad",
        buildsURL: "https://heroeshearth.com/builds/hero/kelthuzad",
        talents: {
            1: ["The Plaguelands", "Blighted Frost", "Barbed Chains"],
            4: [
                "Strip Shields",
                "Phylactery Of Kelthuzad",
                "Armor Of The Archlich",
            ],
            7: ["Accelerated Decay", "Chilling Touch", "Ice Cold"],
            10: ["Frost Blast", "Shadow Fissure"],
            13: ["Icy Grasp", "Chains Of Ice", "Chain Link"],
            16: ["Arcane Echoes", "Hungering Cold", "Power Of Icecrown"],
            20: [
                "Deathchill",
                "Might Of The Scourge",
                "Shifting Malice",
                "The Damned Return",
            ],
        },
    },
    liming: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/0f/Li-ming_square_tile.png/revision/latest?cb=20190326222833",
        urlHeroName: "liming",
        buildsURL: "https://heroeshearth.com/builds/hero/liming",
        talents: {
            1: ["Force Armor", "Aether Walker", "Power Hungry"],
            4: ["Charged Blast", "Triumvirate", "Dominance"],
            7: ["Seeker", "Zeis Vengeance", "Calamity"],
            10: ["Disintegrate", "Wave Of Force"],
            13: ["Illusionist", "Cannoneer", "Glass Cannon"],
            16: ["Fireflies", "Mirrorball", "Arcane Orbit", "Diamond Skin"],
            20: [
                "Temporal Flux",
                "Repulsion",
                "Tal Rashas Elements",
                "Archon Pure Power",
            ],
        },
    },
    lunara: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/9/95/Lunara_square_tile.png/revision/latest?cb=20190326222836",
        urlHeroName: "lunara",
        buildsURL: "https://heroeshearth.com/builds/hero/lunara",
        talents: {
            1: ["Sentinel Wisp", "Natural Perspective", "Hippity Hop"],
            4: ["Blossom Swell", "Siphoning Toxin", "Natures Culling"],
            7: ["Splintered Spear", "Choking Pollen", "Wild Vigor"],
            10: ["Thornwood Vine", "Leaping Strike"],
            13: [
                "Endless Spores",
                "Let Them Wither",
                "Greater Spell Shield",
                "Abolish Magic",
            ],
            16: [
                "Accelerated Contamination",
                "Star Wood Spear",
                "Invigorating Spores",
                "Unfair Advantage",
            ],
            20: [
                "Forests Wrath",
                "Boundless Stride",
                "Intensifying Toxin",
                "Galloping Gait",
            ],
        },
    },
    mephisto: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/5/57/Mephisto_square_tile.png/revision/latest?cb=20190326222842",
        urlHeroName: "mephisto",
        buildsURL: "https://heroeshearth.com/builds/hero/mephisto",
        talents: {
            1: ["Unyielding Power", "Furious Spark", "Malicious Intent"],
            4: ["Hateful Mending", "Static Barrier", "Spite"],
            7: ["Ghastly Armor", "Frost Storm", "Trickery"],
            10: ["Consume Souls", "Durance Of Hate"],
            13: ["Abhorred Skull", "Hysteria", "Shard Of Hate"],
            16: ["Lightning Reaction", "Static Field", "Animosity"],
            20: [
                "Consumed By Hatred",
                "Unspeakable Horror",
                "Mimic",
                "Shade Lord",
            ],
        },
    },
    nazeebo: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/9/91/Nazeebo_square_tile.png/revision/latest?cb=20190326222846",
        urlHeroName: "nazeebo",
        buildsURL: "https://heroeshearth.com/builds/hero/nazeebo",
        talents: {
            1: ["Widowmakers", "Pandemic", "Thing Of The Deep"],
            4: ["Hexed Crawlers", "Big Voodoo", "Blood Ritual"],
            7: ["Spirit Of Arachyr", "Dead Rush", "Toads Of Hugeness"],
            10: ["Gargantuan", "Ravenous Spirit"],
            13: ["Guardian Toads", "Superstition", "Ice Block"],
            16: ["Spider Colony", "Ring Of Poison", "Soul Harvest"],
            20: [
                "Humongoid",
                "Annihilating Spirit",
                "Vile Infection",
                "Bad Medicine",
            ],
        },
    },
    nova: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/c/ce/Nova_square_tile.png/revision/latest?cb=20190326222846",
        urlHeroName: "nova",
        buildsURL: "https://heroeshearth.com/builds/hero/nova",
        talents: {
            1: ["Longshot", "Covert Ops", "Advanced Cloaking"],
            4: ["Rapid Projection", "Holo Stability", "Covert Mission"],
            7: ["Perfect Shot", "One In The Chamber", "Anti Armor Shells"],
            10: ["Triple Tap", "Precision Strike"],
            13: ["Psionic Efficiency", "Double Tap", "Ionic Force Field"],
            16: ["Explosive Round", "Crippling Shot", "Lethal Decoy"],
            20: ["Fast Reload", "Precision Barrage", "Apollo Suit", "Rewind"],
        },
    },
    orphea: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/e/e4/Orphea_square_tile.png/revision/latest?cb=20190326222849",
        urlHeroName: "orphea",
        buildsURL: "https://heroeshearth.com/builds/hero/orphea",
        talents: {
            1: ["En Pointe", "Growing Nightmare", "Ancestral Strength"],
            4: ["Allegrissimo", "Backbiter", "Chaotic Assault"],
            7: ["Insatiable Orphea", "Ravenous Hunger", "Mind Devourer"],
            10: ["Eternal Feast", "Crushing Jaws"],
            13: ["Determination", "Abyssal Symbiosis", "Invasive Miasma"],
            16: ["Bond Of Anguish", "Dead Magic", "Lurking Terror"],
            20: [
                "Monster Within",
                "Engulfing Oblivion",
                "Eldritch Conduit",
                "Final Toccata",
            ],
        },
    },
    probius: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/9/92/Probius_square_tile.png/revision/latest?cb=20190326222851",
        urlHeroName: "probius",
        buildsURL: "https://heroeshearth.com/builds/hero/probius",
        talents: {
            1: ["Echo Pulse", "Warp Resonance", "Gather Minerals"],
            4: ["Photon Barrier", "Turbo Charged", "Shield Capacitor"],
            7: ["Particle Accelerator", "Rift Shock", "Tower Defense"],
            10: ["Pylon Overcharge", "Null Gate"],
            13: ["Aggressive Matrix", "Power Overflowing", "Shield Battery"],
            16: [
                "Quantum Entanglement",
                "Gravity Well",
                "Repulsor",
                "Interference",
            ],
            20: [
                "Construct Additional Pylons",
                "Gate Keeper",
                "Shoot Em Up",
                "Probius Loop",
            ],
        },
    },
    raynor: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/7/7b/Raynor_square_tile.png/revision/latest?cb=20190326222853",
        urlHeroName: "raynor",
        buildsURL: "https://heroeshearth.com/builds/hero/raynor",
        talents: {
            1: ["Exterminator", "Veteran Marksman", "Ace In The Hole"],
            4: ["Fight Or Flight", "Sustaining Rounds", "Behemoth Armor"],
            7: ["Heavy Slugs", "Fuel The Rush", "Unstable Compound"],
            10: ["Hyperion", "Raynors Raider"],
            13: ["Line Em Up", "Giddy Up", "Give Me More"],
            16: ["Paint Them Red", "Rallying Cry", "Bounty Hunter"],
            20: [
                "Cavalrys Arrived",
                "Dusk Wing",
                "Raiders Roll",
                "Sergeant Pepper",
                "Execute Orders",
            ],
        },
    },
    "sgt-hammer": {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/1/14/Sgt._hammer_square_tile.png/revision/latest?cb=20190326222858",
        urlHeroName: "sgt-hammer",
        buildsURL: "https://heroeshearth.com/builds/hero/sgt-hammer",
        talents: {
            1: ["Ambush", "Advanced Artillery", "Maelstrom Rounds"],
            4: ["Barricade", "Siege Tactics", "Regenerative Bio Steel"],
            7: [
                "Pulse Detonation Core",
                "Hover Siege Mode",
                "Graduating Range",
            ],
            10: ["Blunt Force Gun", "Napalm Strike"],
            13: [
                "Tactical Mine Deployment",
                "Entrenched",
                "Hyper Cooling Engines",
            ],
            16: ["Mechanical Know How", "Executioner", "Giant Killer Hammer"],
            20: [
                "Orbital Bfg",
                "Advanced Lava Strike",
                "Shrapnel Mines",
                "Ultra Capacitors",
            ],
        },
    },
    sylvanas: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/a/a6/Sylvanas_square_tile.png/revision/latest?cb=20190326222901",
        urlHeroName: "sylvanas",
        buildsURL: "https://heroeshearth.com/builds/hero/sylvanas",
        talents: {
            1: [
                "Might Of The Banshee Queen",
                "Unfurling Shadows",
                "Overwhelming Affliction",
            ],
            4: ["Unstable Poison", "Mercenary Queen", "Possession"],
            7: ["Barbed Shot", "Lost Soul", "Festering Wounds"],
            10: ["Wailing Arrow", "Mind Control"],
            13: ["Cold Embrace", "Windrunner", "Remorseless"],
            16: ["Evasive Fire", "Life Drain", "Will Of The Forsaken"],
            20: [
                "Deafening Blast Sylvanas",
                "Dark Ladys Call",
                "Withering Barrage",
                "Bolt Of The Storm",
            ],
        },
    },
    tassadar: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/d/d6/Tassadar_square_tile.png/revision/latest?cb=20200415200230",
        urlHeroName: "tassadar",
        buildsURL: "https://heroeshearth.com/builds/hero/tassadar",
        talents: {
            1: ["Psi Infusion", "Static Charge", "Khaydarin Amulet 1"],
            4: ["Induction", "Electric Fence", "Plasma Shield"],
            7: ["Beam Alignment", "Psionic Echo", "Arc Discharge"],
            10: ["Archon", "Black Hole"],
            13: ["Feedback", "Shadow Walk", "Oracle"],
            16: ["Thermal Lance", "Psychic Shock", "Executors Will"],
            20: [
                "Twilight Archon",
                "Force Barrier",
                "Kugelblitz",
                "Khalas Gift",
            ],
        },
    },
    tracer: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/a/a0/Tracer_square_tile.png/revision/latest?cb=20190326222906",
        urlHeroName: "tracer",
        buildsURL: "https://heroeshearth.com/builds/hero/tracer",
        talents: {
            1: ["One Two Punch", "Parting Gift", "Tracer Rounds"],
            4: ["Leeching Rounds", "Pulse Generator", "Is That A Health Pack"],
            7: ["Sleight Of Hand", "Focus Fire", "Locked And Loaded"],
            10: ["Sticky Bomb", "Quantum Spike", "Pulse Rounds"],
            13: ["Untouchable", "Jumper", "Telefrag"],
            16: ["Bullet Spray", "Heavy Handed", "Ricochet"],
            20: [
                "Chrono Triggers",
                "Get Stuffed",
                "Total Recall",
                "Composition B",
            ],
        },
    },
    tychus: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/b/b6/Tychus_square_tile.png/revision/latest?cb=20190326222907",
        urlHeroName: "tychus",
        buildsURL: "https://heroeshearth.com/builds/hero/tychus",
        talents: {
            1: ["Press The Advantage", "Dash", "Quarterback"],
            4: ["In The Rhythm", "The Bigger They Are", "Master Assassin"],
            7: ["Combat Tactician", "Melting Point", "Relentless Soldier"],
            10: ["Commandeer Odin", "Drakken Laser Drill"],
            13: ["Spray N Pray", "Thats The Stuff", "Neosteel Coating"],
            16: ["Armor Piercing Rounds", "Titan Grenade", "Sizzlin Attacks"],
            20: [
                "Big Red Button",
                "Focusing Diodes",
                "Can Do This All Day",
                "Bob And Weave",
            ],
        },
    },
    valla: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/9/9f/Valla_square_tile.png/revision/latest?cb=20190326222912",
        urlHeroName: "valla",
        buildsURL: "https://heroeshearth.com/builds/hero/valla",
        talents: {
            1: ["Puncturing Arrow", "Fire At Will", "Creed Of The Hunter"],
            4: ["Arsenal", "Death Dealer", "Repeating Arrow"],
            7: ["Monster Hunter", "Frost Shot", "Hot Pursuit"],
            10: ["Strafe", "Rain Of Vengeance"],
            13: ["Siphoning Arrows", "Tempered By Discipline", "Gloom"],
            16: ["Punishment", "Seething Hatred", "Manticore"],
            20: [
                "Death Siphon",
                "Storm Of Vengeance",
                "Acrobat",
                "Farflight Quiver",
            ],
        },
    },
    zagara: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/5/57/Zagara_square_tile.png/revision/latest?cb=20190326222917",
        urlHeroName: "zagara",
        buildsURL: "https://heroeshearth.com/builds/hero/zagara",
        talents: {
            1: ["Volatile Acid", "Corpse Feeders", "Infest"],
            4: ["Envenomed Spines", "Medusa Blades", "Serrated Spines"],
            7: ["Baneling Massacre", "Viscous Acid", "Bile Drop"],
            10: ["Devouring Maw", "Nydus Network"],
            13: ["Hydralisk Transfusion", "Protective Coating", "Spell Shield"],
            16: ["Corrosive Saliva", "Mutalisk", "Jagged Barbs"],
            20: [
                "Tyrant Maw",
                "Endless Creep",
                "Broodmother",
                "Pack Instincts",
            ],
        },
    },
    zuljin: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/01/Zul%27jin_square_tile.png/revision/latest?cb=20190326222921",
        urlHeroName: "zuljin",
        buildsURL: "https://heroeshearth.com/builds/hero/zuljin",
        talents: {
            1: ["Boneslicer", "Recklessness", "Headhunter"],
            4: ["Trolls Blood", "Voodoo Shuffle", "Amani Hide"],
            7: ["Vicious Assault", "Arcanite Axes", "Ferocity"],
            10: ["Tazdingo", "Guillotine"],
            13: ["Lacerate", "Eye Of Zuljin", "Ensnare"],
            16: ["No Mercy", "Wrong Place Wrong Time", "Let The Killing Begin"],
            20: [
                "Amani Resilience",
                "Buzzsaw",
                "Forest Medicine",
                "A Surprise For Ya",
            ],
        },
    },
    abathur: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/b/b6/Abathur_square_tile.png/revision/latest?cb=20190326222743",
        urlHeroName: "abathur",
        buildsURL: "https://heroeshearth.com/builds/hero/abathur",
        talents: {
            1: [
                "Pressurized Glands",
                "Envenomed Nest",
                "Reinforced Carapace",
                "Survival Instincts",
            ],
            4: ["Adrenal Overload", "Needlespine", "Prolific Dispersal"],
            7: ["Vile Nest", "Networked Carapace", "Calldown Mule"],
            10: ["Ultimate Evolution", "Evolve Monstrosity"],
            13: ["Spatial Efficiency", "Soma Transference", "Bombard Strain"],
            16: [
                "Envenomed Spikes",
                "Adrenaline Boost",
                "Volatile Mutation",
                "Locust Brood",
            ],
            20: [
                "Evolutionary Link",
                "Evolution Complete",
                "Hivemind",
                "Locust Nest",
            ],
        },
    },
    medivh: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/f/fa/Medivh_square_tile.png/revision/latest?cb=20190326222842",
        urlHeroName: "medivh",
        buildsURL: "https://heroeshearth.com/builds/hero/medivh",
        talents: {
            1: ["Winds Of Celerity", "Ravens Intellect", "Portal Mastery"],
            4: ["Mage Armor", "Raven Familiar", "Dust Of Appearance"],
            7: ["Mystic Assault", "Arcane Explosion", "Force Of Magic"],
            10: ["Poly Bomb", "Ley Line Seal"],
            13: ["Circle Of Protection", "Enduring Will", "Reabsorption"],
            16: ["Arcane Charge", "Temporal Flux Medivh", "Stable Portal"],
            20: [
                "Glyph Of Poly Bomb",
                "Medivh Cheats",
                "Guardian Of Tirisfal",
                "Arcane Brilliance",
                "Dust Of Disappearance",
            ],
        },
    },
    "the-lost-vikings": {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/6/66/The_lost_vikings_square_tile.png/revision/latest?cb=20190326222905",
        urlHeroName: "the-lost-vikings",
        buildsURL: "https://heroeshearth.com/builds/hero/the-lost-vikings",
        talents: {
            1: [
                "Olaf The Stout",
                "Spy Games",
                "Explosive Attacks",
                "Viking Bribery",
            ],
            4: [
                "Pain Dont Hurt",
                "Erik The Swift",
                "Its A Sabotage",
                "Mercenary Lord",
            ],
            7: ["Baleog The Fierce", "Spin To Win", "Norse Force"],
            10: ["Longboat Raid", "Play Again"],
            13: ["Hunka Burning Olaf", "Jump", "Nordic Attack Squad"],
            16: [
                "Large And In Charge",
                "Impatience Is A Virtue",
                "64 KB Marathon",
                "Executioner",
            ],
            20: [
                "Ragnarok 'n' Roll!",
                "Checkpoint Reached",
                "The Sequel",
                "Viking Fury Of The Storm",
            ],
        },
    },
    zarya: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/a/a0/Zarya_square_tile.png/revision/latest?cb=20190326222918",
        urlHeroName: "zarya",
        buildsURL: "https://heroeshearth.com/builds/hero/zarya",
        talents: {
            1: [
                "Demolitions Expert",
                "Together We Are Strong",
                "Feel The Heat",
                "Maximum Charge",
            ],
            4: [
                "I Am The Strongest",
                "Give Me Twenty",
                "Speed Barrier",
                "Defensive Shielding",
            ],
            7: ["Pinpoint Accuracy", "Deep Burn", "Explosive Barrier"],
            10: ["Graviton Surge", "Expulsion Zone"],
            13: [
                "Unstoppable Competitor",
                "Spell Barrier",
                "Endurance Training",
                "Pain Is Temporary",
            ],
            16: [
                "Plasma Shock",
                "Cleansing Shield",
                "Gain Train",
                "Born In Battle",
            ],
            20: [
                "Gravity Kills",
                "Clear Out",
                "Grenadier",
                "Unyielding Defender",
            ],
        },
    },
    anubarak: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/7/7f/Anub%27arak_square_tile.png/revision/latest?cb=20190326222746",
        urlHeroName: "anubarak",
        buildsURL: "https://heroeshearth.com/builds/hero/anubarak",
        talents: {
            1: ["Legion Of Beetles", "Nerubian Armor", "Regeneration Master"],
            4: ["Bed Of Barbs", "Shed Exoskeleton", "Underking"],
            7: ["Chitinous Plating", "Subterranean Shield", "Leeching Scarabs"],
            10: ["Locust Swarm", "Cocoon"],
            13: [
                "Burning Beetles",
                "Urticating Spines",
                "Acid Drenched Mandibles",
            ],
            16: ["Epicenter", "Debilitation", "Beetle Juiced"],
            20: ["Hive Master", "Cryptweave", "The Traitor King", "Rewind"],
        },
    },
    arthas: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/e/e4/Arthas_square_tile.png/revision/latest?cb=20190326222749",
        urlHeroName: "arthas",
        buildsURL: "https://heroeshearth.com/builds/hero/arthas",
        talents: {
            1: ["Frost Presence", "Eternal Hunger", "Rime"],
            4: ["Deathlord", "Frozen Wastes", "Icy Talons"],
            7: ["Immortal Coil", "Rune Tap", "Icebound Fortitude"],
            10: ["Army Of The Dead", "Summon Sindragosa"],
            13: ["Shattered Armor", "Biting Cold", "Frost Strike"],
            16: ["Embrace Death", "Remorseless Winter", "Frostmourne Feeds"],
            20: [
                "Legion Of Northrend",
                "Absolute Zero",
                "Deaths Advance",
                "Anti Magic Shell",
            ],
        },
    },
    blaze: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/8f/Blaze_square_tile.png/revision/latest?cb=20190326222752",
        urlHeroName: "blaze",
        buildsURL: "https://heroeshearth.com/builds/hero/blaze",
        talents: {
            1: [
                "Adrenaline Stimpack",
                "Endurance Stimpack",
                "Neural Stimpack",
                "New Habits",
            ],
            4: ["Incinerator Gauntlets", "Oil Dispersal", "Meltdown"],
            7: ["Suppressive Fire", "Nanomachine Coating", "Fuel Leak"],
            10: ["Bunker Drop", "Combustion"],
            13: ["Grill And Kill", "Adhesive Petroleum", "Collision Course"],
            16: ["Thermal Protection", "Heat Treatment", "Juggernaut Plating"],
            20: ["Fortified Bunker", "Flash Fire", "Burn Notice"],
        },
    },
    cho: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/4/43/Cho_square_tile.png/revision/latest?cb=20190326222756",
        urlHeroName: "cho",
        buildsURL: "https://heroeshearth.com/builds/hero/cho",
        talents: {
            1: ["Consuming Fire", "The Will Of Cho", "Calloused Hide"],
            4: ["Uppercut", "Rollback", "Seared Flesh"],
            7: ["Power Surge", "Firestarter", "Enraged Regeneration"],
            10: ["Hammer Of Twilight", "Upheaval"],
            13: ["Surging Dash", "Twilight Veil", "Molten Block"],
            16: ["Frenzied Fists", "Runic Feedback", "Runed Gauntlet"],
            20: [
                "Cthuns Gift",
                "Favor Of The Old Gods",
                "Fuel For The Flame",
                "Hour Of Twilight",
            ],
        },
    },
    diablo: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/00/Diablo_square_tile.png/revision/latest?cb=20190326222801",
        urlHeroName: "diablo",
        buildsURL: "https://heroeshearth.com/builds/hero/diablo",
        talents: {
            1: ["Feast On Fear", "Devils Due", "Soul Shield"],
            4: ["Sacrificial Soul", "Souls To The Flame", "Life Leech"],
            7: ["Eternal Flames", "Malevolence", "Diabolical Momentum"],
            10: ["Apocalypse", "Lightning Breath"],
            13: ["Devastating Charge", "Hellfire", "Cruelty"],
            16: ["Domination", "Debilitating Flames", "Overpowering Nightmare"],
            20: ["Dying Breath", "Hellstorm", "Lord Of Terror", "Hellgate"],
        },
    },
    etc: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/6/6b/E.t.c._square_tile.png/revision/latest?cb=20190326222802",
        urlHeroName: "etc",
        buildsURL: "https://heroeshearth.com/builds/hero/etc",
        talents: {
            1: ["Guitar Hero", "Prog Rock", "Block Party"],
            4: ["Crowd Surfer", "Loud Speakers", "Speed Metal"],
            7: ["Pinball Wizard", "Echo Pedal", "Hammer On"],
            10: ["Mosh Pit", "Stage Dive"],
            13: ["Mic Check", "Encore", "Face Smelt"],
            16: ["Show Stopper", "Aggressive Shredding", "Imposing Presence"],
            20: [
                "Tour Bus",
                "Crowd Pleaser",
                "Death Metal",
                "Storm Shield",
                "Bolt Of The Storm",
            ],
        },
    },
    garrosh: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/03/Garrosh_square_tile.png/revision/latest?cb=20190326222809",
        urlHeroName: "garrosh",
        buildsURL: "https://heroeshearth.com/builds/hero/garrosh",
        talents: {
            1: [
                "Warbreaker",
                "Unrivaled Strength",
                "Body Check",
                "Into The Fray",
            ],
            4: ["In For The Kill", "Thirst For Battle", "Indomitable"],
            7: ["Intimidation", "Brute Force", "Oppressor"],
            10: ["Warlords Challenge", "Decimate"],
            13: ["Defensive Measures", "Bloodcraze", "Double Up"],
            16: ["Seasoned Soldier", "Mortal Combo", "Earthshaker"],
            20: ["Death Wish", "Deadly Calm", "Titanic Might", "Inner Rage"],
        },
    },
    johanna: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/e/e5/Johanna_square_tile.png/revision/latest?cb=20190326222825",
        urlHeroName: "johanna",
        buildsURL: "https://heroeshearth.com/builds/hero/johanna",
        talents: {
            1: ["Laws Of Hope", "Zealous Glare", "Divine Fortress"],
            4: ["Eternal Retaliation", "Subdue", "Hold Your Ground"],
            7: ["Sins Exposed", "Conviction", "Steed Charge"],
            10: ["Falling Sword", "Blessed Shield"],
            13: ["Roar", "Holy Fury", "Blessed Hammer"],
            16: ["Holy Renewal", "Blessed Momentum", "Shrinking Vacuum"],
            20: [
                "Heavens Fury",
                "Radiating Faith",
                "Indestructible",
                "Blinded By The Light",
            ],
        },
    },
    malganis: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/7/74/Mal%27ganis_square_tile.png/revision/latest?cb=20190503090708",
        urlHeroName: "malganis",
        buildsURL: "https://heroeshearth.com/builds/hero/malganis",
        talents: {
            1: ["Winged Guardian", "Vampiric Aura", "Time To Feed"],
            4: ["Fueled By Torment", "Might Of Sargeras", "Echo Of Doom"],
            7: [
                "Black Claws",
                "Will Of Tichondrius",
                "Spreading Plague",
                "Nightmare Fuel",
            ],
            10: ["Carrion Swarm", "Dark Conversion"],
            13: ["Deep Sleep", "The Night Beckons", "Blood Rush"],
            16: ["Plague Bats", "Frenzied Assault", "Blind As A Bat"],
            20: [
                "Seeker Swarm",
                "Wrath Of Nathreza",
                "Vanquish The Weak",
                "Alone In The Dark",
            ],
        },
    },
    mei: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/0/08/Mei_square_tile.png/revision/latest?cb=20200617121830",
        urlHeroName: "mei",
        buildsURL: "https://heroeshearth.com/builds/hero/mei",
        talents: {
            1: ["Heavy Pack", "Ice Storm", "Heat Transfer"],
            4: ["Slushball", "Cold Front", "Crystallize"],
            7: ["Induce Hibernation", "Skating Away", "Backup Battery"],
            10: ["Avalanche", "Ice Wall"],
            13: ["Flurry", "Cooling Servos", "Polar Vortex"],
            16: ["Fresh Powder", "Black Ice", "Acclimation"],
            20: ["Cascade", "Shatter", "The Big One", "Flash Freeze"],
        },
    },
    muradin: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/8/84/Muradin_square_tile.png/revision/latest?cb=20190326222843",
        urlHeroName: "muradin",
        buildsURL: "https://heroeshearth.com/builds/hero/muradin",
        talents: {
            1: ["Perfect Storm", "Third Wind", "Dwarf Block"],
            4: ["Sledgehammer", "Reverberation", "Thunder Burn"],
            7: ["Heavy Impact", "Give Em The Axe", "Skullcracker"],
            10: ["Avatar", "Haymaker"],
            13: ["Healing Static", "Thunder Strike", "Bronzebeard Rage"],
            16: ["Dwarf Launch", "Imposing Presence", "Stoneform"],
            20: [
                "Unstoppable Force",
                "Grand Slam",
                "Hardened Shield",
                "Rewind",
            ],
        },
    },
    stiches: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/f/fd/Stitches_square_tile.png/revision/latest?cb=20190326222859",
        urlHeroName: "stitches",
        buildsURL: "https://heroeshearth.com/builds/hero/stitches",
        talents: {
            1: ["Savor The Flavor", "Patchwork Creation", "Hungry For More"],
            4: ["Playtime", "Tenderizer", "Vile Cleaver"],
            7: ["Blight", "Serrated Edge", "Second Helping", "Putrefaction"],
            10: ["Putrid Bile", "Gorge"],
            13: ["Meat Hook", "Under Pressure", "Chop Chop"],
            16: ["Digestive Juices", "Flare Up", "Pulverize"],
            20: [
                "Hungry Hungry Stitches",
                "Gift From The Embalmer",
                "Master Hooker",
                "Gas Bag",
            ],
        },
    },
    tyrael: {
        avatar: "https://static.wikia.nocookie.net/allstars_gamepedia/images/2/28/Tyrael_square_tile.png/revision/latest?cb=20190326222908",
        urlHeroName: "tyrael",
        buildsURL: "https://heroeshearth.com/builds/hero/tyrael",
        talents: {
            1: ["Salvation", "Justice For All", "Ardent Restoration"],
            4: ["Stalwart Angel", "Bound By Law", "Divine Vigor"],
            7: ["Reciprocate", "Purge Evil", "Swift Retribution"],
            10: ["Judgment", "Sanctification"],
            13: ["Sword Of Justice", "Holy Ground", "Law And Order"],
            16: ["Horadric Reforging", "Burning Halo", "Smite The Wicked"],
            20: [
                "Angel Of Justice",
                "Holy Arena",
                "Defense Of The Angels",
                "Seal Of Eldruin",
            ],
        },
    },
};
